export const experienceList = [
  {
    company: "Bettershore, Switzerland",
    companyUrl: "https://www.bettershore.com/",
    position: "Frontend Engineer (Semi-Senior)",
    startDate: "2025",
    endDate: "Present",
    location: "Switzerland",
    description: [
      "- Developed and maintained advanced Next.js and React.js applications that reduced load times by up to 35% and improved user engagement by 40%.",
      "- Maintained direct communication with a major Swedish client, who has expressed high satisfaction with the quality and innovation of the solutions delivered.",
      "- Integrated advanced caching, lazy loading, bundler reduction, and other performance optimization techniques, significantly boosting application speed and user satisfaction.",
    ],
    technologies: [
      "Next.js",
      "React.js",
      "TypeScript",
      "PostgreSQL",
      "DrizzleORM",
      "React Query",
      "HTML",
      "CSS",
      "Tailwind CSS",
      "Shadcn UI",
      "React Hook Forms",
      "Zod",
      "Git",
      "Linear",
      "CI/CD",
      "JavaScript",
    ],
    softSkills: [
      "Client Communication",
      "Performance Optimization",
      "Technical Leadership",
      "Problem Solving",
      "Innovation",
    ],
  },
  {
    company: "Globant, Argentina",
    companyUrl: "https://www.globant.com/",
    position: "Frontend Engineer (Intern)",
    startDate: "2024",
    endDate: "2024",
    location: "Argentina",
    description: [
      "- Led the architectural design for the Gloobcamp project, enabling the seamless integration of five new functionalities.",
      "- Mentored team members in advanced Next.js and TypeScript techniques, resulting in a 50% improvement in autonomous problem-solving skills.",
      "- Refactored core components, achieving a 30% boost in loading speed and perfecting Lighthouse performance scores for accessibility and overall performance.",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "React",
      "JavaScript",
      "Tailwind CSS",
      "GraphQL",
      "Redux",
      "Apollo Client",
      "Storybook",
      "Git",
      "GitHub",
      "Jest",
      "React Testing Library",
      "Webpack",
      "ESLint",
      "Lighthouse",
      "Google Analytics",
      "PageSpeed Insights",
      "Figma",
      "Agile",
      "Scrum",
    ],
    softSkills: [
      "Leadership",
      "Mentoring",
      "Problem Solving",
      "Technical Architecture",
      "Performance Optimization",
    ],
  },
  {
    company: "Professional Independent",
    position: "Fullstack Engineer - E-commerce & Business Management",
    startDate: "2022",
    endDate: "2024",
    location: "Argentina",
    description: [
      "- Delivered end-to-end freelance projects leveraging React.js, achieving an average 30% performance improvement across client applications.",
      "- Partnered directly with clients to capture requirements, design UI/UX prototypes, and build scalable web solutions, maintaining a client satisfaction rate above 90%.",
      "- Developed custom solutions integrating modern front-end libraries and RESTful APIs, contributing to a 20% increase in project revenue.",
      "- Managed complete project lifecycles in agile settings, coordinating with multidisciplinary teams to ensure on-time delivery and high-quality outcomes.",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Redux",
      "React Query",
      "Astro",
      "HTML",
      "CSS",
      "Styled Components",
      "Tailwind CSS",
      "Bootstrap",
      "SaSS",
      "React Hook Forms",
      "Zod",
      "Jest",
      "React Testing Library",
      "Git",
      "Scrum",
      "Kanban",
      "Jira",
      "Linear",
      "Agile",
      "Nest.js",
      "Node.js",
      "Express.js",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Swagger",
      "PostgreSQL",
    ],
    softSkills: [
      "Client Management",
      "Project Management",
      "Team Coordination",
      "Problem Solving",
      "Business Development",
      "Agile Leadership",
    ],
  },
];
